// pages/api/hellocoop.js
// generated by @hellocoop/quickstart --nextjs on 2025-03-24T14:54:53.177Z
// NOTE: this file should not need to be edited
import config from '../../hello.config'
import { pageAuth } from '@hellocoop/nextjs'
export default pageAuth(config)
